version: 2
updates:
# barista-api
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/barista-api" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    

# barista-scan
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/barista-scan" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
      
# barista-web
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/barista-web" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"

# github-actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
